---
sa_items: []

sa_languages:
- en-US
sa_default_language: en-US

sa_feed_items_importation_types: []

sa_ws_types: []

sa_item_categories: []

sa_allowed_free_user_creation: "false"
sa_automatic_private_workspace: "true"
sa_mandatory_user_activation: "true"

sa_application_name: ThinkDRY BLANK Application
sa_application_url: http://blank.thinkdry.com
sa_favicon_url: /config_files/favicon.ico
sa_logo_url: /config_files/logo.jpg
sa_per_page_default: 10
sa_default_layout: "app_fat_menu"
sa_exception_notifier_activated: "false"
sa_contact_email: ""

sa_layouts: []
sa_exception_followers_email: []
sa_default_language: "en-US"

