--- 
:backgroundrb:
  :ip: 0.0.0.0
  :port: 11006
  :environment: <%= RAILS_ENV %>
:memcache: "10.0.0.1:11211,10.0.0.2:11211"
#:schedules:
#  :converter_worker:
  #  :encoder:
  #    :trigger_args: 1 * * * *
