--- 
sa_ws_types: 
- public
- closed

ws_types: []


sa_feed_items_importation_types: 
- bookmark

sa_items: 
- article
- audio
- feed_source
- cms_file
- image
- video
sa_feed_items_importation_types: 
- bookmark
sa_languages: 
- en-US
